# Generated by Django 2.1.2 on 2019-03-15 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('explain', models.CharField(max_length=20)),
                ('skillpoint', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('main', models.IntegerField(default=1)),
                ('token', models.UUIDField(default=uuid.UUID('1353b424-477e-11e9-8d21-7c763549e4c1'), unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ニックネーム')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('level', models.IntegerField(default=1)),
                ('explain', models.CharField(max_length=20)),
                ('token', models.UUIDField(default=uuid.UUID('1353b425-477e-11e9-818b-7c763549e4c1'), unique=True)),
                ('Job_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bok.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=30)),
                ('time', models.IntegerField(default=0)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.UUIDField(default=uuid.UUID('13549e8a-477e-11e9-9899-7c763549e4c1'), unique=True)),
                ('Job_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bok.Job')),
                ('player_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bok.Player')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='player_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bok.Player'),
        ),
    ]
